### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by TehFoxFire** [someaddons/SavageEnderDragon#12]
### Describe the bug you're experiencing

Client Crashes when you damage the dragon.

### Reproducability

1.18.2 MC, Forge 40.0.17, punch the dragon.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.18.1

### Modloader version

Forge

### Logs

https://gist.github.com/TehFoxFire/14ebb961517f82da215cde724365c3b8

**Comment by someaddons** [comment]
yea mojang broke stuff, fixed in 2.0
