### ISSUE TITLE
Suggestion: Configuration for lightning summon frequency

### ISSUE THREAD

**Issue by Fourbo** [someaddons/SavageEnderDragon#13]
I tried out the Ender Dragon fight and I think the different aspects you added are all really cool but I felt like having so many lightning bolts spawning every 2-3 seconds might get to annoying for some players (I couldn't tell if the lightning is supposed to follow you or not  cause it seemed to at times but other times it just spawned in a circle). 
Having so much lightning also causes the game to stutter very briefly, so I thought maybe there could be a config option to change frequency or amount of lightning that's spawned, since all the other features seem to blend well together.
I tried reducing the difficulty modifier to 0 but I didn't notice a difference with this mechanic.
And thank you for the great work on the mod.

**Comment by someaddons** [comment]
Its an outwards-advancing circle which makes it more difficult for the player to get close

**Comment by yukami-neesan** [comment]
Yeah it stutter the game because of too many lightning at once, should've spread it out over a few seconds or make it strike random,ect...

**Comment by Fourbo** [comment]
Yeah I think it's a great addition and it makes the fight more chaotic, I would just notice the brief stutter each time.

**Comment by someaddons** [comment]
added a config, the lag/stutter probably originates from shaders, those like to spice up lightning which can get laggy
