### ISSUE TITLE
[Feature Request]: Config adjustments for amounts

### ISSUE THREAD

**Issue by SpigotDE** [someaddons/SavageEnderDragon#14]
Would be nice to add a amount of endermans or creepers or other mod mobs to the config

For Example:

When Dragon is sitting in the middle -> Enderman spawn & Creeper Spawn ( cause of my config ) 

Now i wanna say that only 1 creeper spawns or only 1 modded creature spawns

the same goes for crystal respawn/destroy -> i wanna add a modded creature that is really strong and when 2 or more spawns its tooo hard to fight against

**Comment by someaddons** [comment]
the amount constributes to the difficulty of the fight and thus scales with the dynamic difficulty itself, so cannot really reduce that to just a certain value

**Comment by someaddons** [comment]
crystal destroy creatues btw only spawn when it is killed from a range
