### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Jetpack-Cat** [someaddons/SavageEnderDragon#15]
### Describe the bug you're experiencing

How do I prevent the ender dragon from spawning 70 mobs when he's in the center? It destroys performance and makes the mod unusable

[crash-2022-04-26_17.36.36-server.txt](https://github.com/someaddons/SavageEnderDragon/files/8567724/crash-2022-04-26_17.36.36-server.txt)

### Reproducability

#List of mobs spawning while the dragon is sitting in the middle, intended to be melee and not vulnerable to ranged: e.g. format :  ["minecraft:zombie", "minecraft:creeper"]
	spawnwhilelanded = []

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.16.5

### Modloader version

Forge

### Logs

uploaded above

**Comment by someaddons** [comment]
that is a side effect of setting the config difficulty too high, on which value did you set that?

**Comment by someaddons** [comment]
updated the scaling to work a bit better in 1.8
