### ISSUE TITLE
[Bug]: Ender Dragon HP changes don't apply on respawn

### ISSUE THREAD

**Issue by MaliciousZoroark** [someaddons/SavageEnderDragon#16]
### Describe the bug you're experiencing

If you respawn the Ender Dragon via End Crystal, it will have 200 health. Minecraft Version 1.18.2

### Reproducability

1) Kill the Dragon
2)Place End Crystals on the necessary spots to respawn the Dragon after killing it

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.18.1

### Modloader version

Fabric

### Logs

https://paste.ee/p/Izvot

**Comment by someaddons** [comment]
The dragon's hp is updated when the fight starts

**Comment by itsdinkd** [comment]
This also breaks any attribute modifications you make to the dragon. 

For example, I have set Ender Dragon to be a eldritch mob, all the time. Eldritch mobs have 4x health. With Savage ender dragon, it ignores the hp change.
