### ISSUE TITLE
【Bug】It seem does't work in 1.19.2-Forge

### ISSUE THREAD

**Issue by blood789** [someaddons/SavageEnderDragon#23]
### Describe the bug you're experiencing

1. No Lightning when fight with dragon.
2. The crystal do not respawn.
3. The bed can explode in the end , and it can hurt the dragon, please stop it.

### Reproducability

-

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.18.1

### Modloader version

Forge

### Logs

-

**Comment by siarapis** [comment]
its not working for me in 1.92.2 forge  version
