### ISSUE TITLE
1.14.9 Fabric, Minecraft 1.19.2, Illusioner is not attacking player

### ISSUE THREAD

**Issue by RogueOne529** [someaddons/SavageEnderDragon#25]
When I alter the config file, changing the original written mobs in either "spawnwhenlanded" (phantom by default), "spawnoncrystaldestroy" (blaze by default) or "spawnoncrystalrespawn" (enderman by default) to the mob illusioner, the illusioner behavior is not normal as intended, casting illusions of themselves but do not attack me as it glitched?

I was confused thus I bring up vanilla in-game command to /summon illusioner and it did summoned an illusioner that is hostile and attack me on sight. 

As far as I know, illusioner is hostile and not passive, tested in single player. I really look forward to add illusioner in battle since they do not spawn naturally anywhere.

**Comment by someaddons** [comment]
fixed
