### ISSUE TITLE
[Bug]: Crash on empty List

### ISSUE THREAD

**Issue by RedstoneGamer123** [someaddons/SavageEnderDragon#27]
### Describe the bug you're experiencing

When I leave spawn while landed as [] in the config the server crashed due to bound not being positive. Should not be required to have an entity in the list.

### Reproducability

empty the mob spawning list.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.18

### Modloader version

Forge

### Logs

https://gist.github.com/RedstoneGamer123/747158bd3bc93f573d83d1d62f8c719d

**Comment by someaddons** [comment]
fixed
