### ISSUE TITLE
The server outputs the following warnings on the command line

### ISSUE THREAD

**Issue by chen-Futuro** [someaddons/SavageEnderDragon#29]
I put it on the fabric1.18.2 server and output the following information on the command line. Will my game be affected? Can this warning be fixed?

[12:17:49 ERROR] [main]: [DragonfightMod] Could not parse config file
java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonElement.getAsJsonObject()" because the return value of "com.google.gson.JsonObject.get(String)" is null

**Comment by someaddons** [comment]
just mean the config couldnt be read and uses default values instead, not a big issue. Closing this since I wont be upadting old versions for fabric
