### ISSUE TITLE
Feature Request: Config additions

### ISSUE THREAD

**Issue by Tyrius1** [someaddons/SavageEnderDragon#3]
A config to change what mob is spawned. I'd like to swap out enderman for modded mobs.
A config to tweak how many of said mobs spawn when they are spawned?
A config to change what mobs and how many are spawned when breaking crystals.

**Comment by someaddons** [comment]
the amount spawns scales with difficulty and ye I can add a config to select which are spawned. Although the current ones are intentionally chosen with their different abilities: Ranged(+burn), Melee(enderman) for the players closer and flying phantoms for the people shooting crystals with bows

**Comment by someaddons** [comment]
added in 1.7

**Comment by Tyrius1** [comment]
I completely missed this... Thank you for adding this in!!
