### ISSUE TITLE
[Bug]: Mobs Spawn with no weapons

### ISSUE THREAD

**Issue by SovietPika** [someaddons/SavageEnderDragon#30]
### Describe the bug you're experiencing

I added mobs such as "minecraft:stray", "minecraft:vindicator" to the config. They spawn but they spawn with no weapons. Is there a way to add NBT data to the mobs in the config so I can make them spawn with the weapons/also give them potion effects?

### Reproducability

Add any mob that should have a weapon to the config they spawn but without that weapon.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19

### Modloader version

Forge

### Logs

No logs generated when mobs are spawned

**Comment by someaddons** [comment]
fixed
