### ISSUE TITLE
[Bug]: Enderman not spawning even after adjusting .toml configs

### ISSUE THREAD

**Issue by lcocs** [someaddons/SavageEnderDragon#31]
### Describe the bug you're experiencing

I didn't notice that the endermen weren't spawning, so I proceeded to build an exp farm and only noticed the missing enderman after. Searched a bit and found the .toml to configurate the spawn on the main island. Even after changing "Disables mob spawning on the Dragon island" to false, the enderman did not spawn after restarting the game. Can I change it some way? Really wanted the exp...

### Reproducability

The .toml does not work.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19

### Modloader version

Forge

### Logs

https://gist.github.com/lcocs/6cada7e43a9b1dc6caad8008144540b1

**Comment by someaddons** [comment]
![image](https://user-images.githubusercontent.com/38401808/215167584-52a1e72f-d21b-470a-b3ac-e6a009294234.png)
works fine for me
