### ISSUE TITLE
[Bug]: The mod name isn't the mod name

### ISSUE THREAD

**Issue by aaronhowser1** [someaddons/SavageEnderDragon#32]
### Describe the bug you're experiencing

The mod's file and name in the mod list is `Dragonflight Mod`, while everywhere else the mod is called `Savage Ender Dragon`. Makes it hard to find if you don't think to check the mod page's file downloads list.

### Reproducability

N/A

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19

### Modloader version

Fabric

### Logs

N/A

**Comment by Proxwian** [comment]
bump
