### ISSUE TITLE
[Bug]: 1.19.4 Update

### ISSUE THREAD

**Issue by IAmSneak** [someaddons/SavageEnderDragon#33]
### Describe the bug you're experiencing

Mod no longer works in latest minecraft release.

### Reproducability

Load mod in 1.19.4

### Mod up to date

- [x] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19

### Modloader version

Fabric

### Logs

https://gist.github.com/IAmSneak/22eaf7908e7d8ac16374c3d6d683065c

**Comment by someaddons** [comment]
fixed
