### ISSUE TITLE
[Bug]: Crash on "respawn crystal" and "spawn melee (blaze?)"

### ISSUE THREAD

**Issue by dlfnn** [someaddons/SavageEnderDragon#35]
### Describe the bug you're experiencing

I'm making a heavy modpack which might be the reason why this crash happens ; _;

### Reproducability

Start the dragon fight, kill some crystals and wait for the dragon to respawn them

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19

### Modloader version

Fabric

### Logs

https://gist.github.com/dlfnn/fbf33b82251b0e83644c0fcb4fade8ca/edit (Crash report

**Comment by someaddons** [comment]
fixed
