### ISSUE TITLE
[Bug]: Server Crash When Fighting with the End Dragon.

### ISSUE THREAD

**Issue by OcrSu** [someaddons/SavageEnderDragon#36]
### Describe the bug you're experiencing

Fighting with the End Dragon，and The Server Crashes.

### Reproducability

Fighting with the End Dragon，and The Server Crashes.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.18

### Modloader version

Forge

### Logs

https://gist.github.com/OcrSu/f2c6f3ae78bc730ed166e02c7b2675c4

**Comment by someaddons** [comment]
version 1.18 does not support removed all spawning entities from its config, that only works on 1.19+. 
Not going to update that on 1.18 anymore
