### ISSUE TITLE
[Perfomance issue]: Terrible server performance after dragon damaged.

### ISSUE THREAD

**Issue by KostromDan** [someaddons/SavageEnderDragon#37]
### Describe the bug you're experiencing

After the HP of the dragon becomes not 100%, the main thread of the server, no matter how powerful the processor is (7950x tested), it will be loaded at 100%. On weaker processors, a drop in tps for 300 begins and terrible lags.
![image](https://github.com/someaddons/SavageEnderDragon/assets/90044015/93038635-40ee-431d-ac89-9a02e520be0b)
![image](https://github.com/someaddons/SavageEnderDragon/assets/90044015/1d06995f-10a0-4e9c-b127-46162de5fe30)
![image](https://github.com/someaddons/SavageEnderDragon/assets/90044015/b69fb23f-0ec9-48d1-86dd-6efb5f533ca3)
https://spark.lucko.me/YxwZOHMcAk

### Reproducability

-

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19

### Modloader version

Forge

### Logs

-

**Comment by someaddons** [comment]
report it to alex mobs, lag is from 
![image](https://github.com/someaddons/SavageEnderDragon/assets/38401808/25ef0070-79f9-4274-8cfe-dede65078c8b)

When the dragon is damaged it disables mob spawning around it, triggering the bug
