### ISSUE TITLE
[Bug]: Mixin failing to inject

### ISSUE THREAD

**Issue by TenerPVPs** [someaddons/SavageEnderDragon#38]
### Describe the bug you're experiencing

mixin failing to inject as i said, no crash, but i think its a problem isnt it?

### Reproducability

forge 43.2.12

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19

### Modloader version

Forge

### Logs

https://gist.github.com/TenerPVPs/cb5659178a763688f32de5e0567b1e01

**Comment by someaddons** [comment]
its not necessary to run, but you're using two dragon modifying mods, so some conflict/incompat is to be expected
