### ISSUE TITLE
[Question] Can this mod edit the amount of XP that the Dragon drops?

### ISSUE THREAD

**Issue by Yokiie** [someaddons/SavageEnderDragon#39]
I apologize for using Issues to ask the question but I couldn't find another way to contact you directly.

My questions is simple : Can this mod edit the amount of XP that the Dragon drops?
After it's slain for the 1st time & drops 12'000 XP, all later kills only drop 500 XP. Would this mod be able to fix that to make the Dragon slaying more rewarding on my multiplayer server ?

I'd also love to know if it's possible to add XP sharing between players ? So not only the closest player gets all the XP, but if you're "raiding" the dragon with other people, everyone gets a share.

**Comment by someaddons** [comment]
I could add that ye

**Comment by someaddons** [comment]
added in 4.2
