### ISSUE TITLE
Are endermen supposed to start spawning after the dragon fight?

### ISSUE THREAD

**Issue by mosharky** [someaddons/SavageEnderDragon#4]
Unsure if this is intended or not, but Endermen aren't spawning as normal in vanilla after the fight. I'm using the dragonfight-1.5 1.16.5 version.

**Comment by someaddons** [comment]
atm it disables the enderman spawns on the dragon island, as vanilla's super fast spawn rate interferes with the fight

**Comment by mosharky** [comment]
> atm it disables the enderman spawns on the dragon island, as vanilla's super fast spawn rate interferes with the fight

Would definitely like a toggle in the config on that if possible

**Comment by someaddons** [comment]
sure

**Comment by someaddons** [comment]
added in 1.7

**Comment by IPlayMinecraftYT** [comment]
> added in 1.7

There is no config button for the mod. I am currently using Valhelsia Enhanced Vanilla 1.2.1
