### ISSUE TITLE
[Bug]: Spawning incorrect mobs

### ISSUE THREAD

**Issue by Shipmans-AGLA** [someaddons/SavageEnderDragon#40]
### Describe the bug you're experiencing

Changing the mobs spawned in the config to mobs from other mobs spawns incorrect mobs. For example, i put minecells:kamikaze, and a zombie pigman spawned instead. putting minecells:mutated_bat spawned a pig. In addition to this, attempting to disabled some mob spawns by putting nothing crashed the game, and putting minecraft:empty spawned a pig.

### Reproducability

change the mob spawned for crystal destruction/respawning to a mob from another mod, then break a crystal or wait for the dragon to respawn a crystal.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19

### Modloader version

Fabric

### Logs

https://gist.github.com/Shipmans-AGLA/8bcd1de765a3377a24598e3ba3abc91a

**Comment by someaddons** [comment]
fixed in 3.9
