### ISSUE TITLE
[Bug]: Particles entity stays forever after crystal destroying

### ISSUE THREAD

**Issue by Proxwian** [someaddons/SavageEnderDragon#41]
### Describe the bug you're experiencing

![image](https://github.com/someaddons/SavageEnderDragon/assets/31781674/0cce1f8d-9604-4cce-a005-2e738ecf7a38)

When breaking ender crystal at main island, these particles doesn't allow to place new blocks nearby and spawn new dragon. Is there any way yo disable them?

### Reproducability

Kill enderdragon
Place endercrystal near portal
Destroy it
Have particles forever going

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.18

### Modloader version

Forge

### Logs

https://gist.github.com/

**Comment by someaddons** [comment]
those are time based upon breaking, they vanish after a bit
