### ISSUE TITLE
[Question] Is there a way to add NBT tags to mobs spawned when, for example, a crystal is destroyed? Like making a creeper a charged creeper

### ISSUE THREAD

**Issue by PiscoWithinTheMist** [someaddons/SavageEnderDragon#42]
I tried using "minecraft:creeper{powered:1}" with and without spaces, but that command is for /summon only.
I guess the way to go would be summoning both "minecraft:creeper", "minecraft:lightning_bolt" but thats not ideal ofc.
Thanks in advance.

**Comment by someaddons** [comment]
added in newest
