### ISSUE TITLE
[Bug]: Respawning crystals will spawn on blocks above the obsidian end pillars

### ISSUE THREAD

**Issue by Voltem0** [someaddons/SavageEnderDragon#43]
### Describe the bug you're experiencing

With YUNG's better end island
https://www.curseforge.com/minecraft/mc-mods/yungs-better-end-island
the end pillars spawn in these really cool obsidian spikes rather than the standard obsidian monoliths

The boss fight of this mod works as normal but because of these spikes the 'respawning' end crystals will occasionally spawn on one of the obsidian blocks above the bedrock blocks rather than the actual bedrock blocks, as im fairly sure the mod gets confuses as to where it should spawn the respawning crystals. The usual 'bedrock' base of the crystal will be replaced with the obsidian equivalent too.

Doesnt make it unbeatable by any means its just occasionally slightly off. Seems indicative that it could spawn on other blocks as well as long as they are above the bedrock blocks, though i have not tested that..

### Reproducability

I play on 1.20.1, with forge 47

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19

### Modloader version

Forge

### Logs

no

**Comment by someaddons** [comment]
Fixed in 4.2
