### ISSUE TITLE
[Bug]: CurseForge listing for mod says "Requires Cuboard dependency to be installed on newer versions" instead of Cupboard

### ISSUE THREAD

**Issue by Brody0727** [someaddons/SavageEnderDragon#44]
### Describe the bug you're experiencing

The description on the CurseForge page for Savage Ender Dragon says "cuboard" instead of "cupboard"

### Reproducability

1. Use the internet
2. Look at Forge
3. Description is sus

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19

### Modloader version

Forge

### Logs

There's no log, it's literally a spelling error

**Comment by someaddons** [comment]
fixed
