### ISSUE TITLE
[BUG]: Endermen still spawn 

### ISSUE THREAD

**Issue by BodhiSmith13** [someaddons/SavageEnderDragon#45]
### Describe the bug you're experiencing

Endermen still spawn through vanilla means on the end island. 

### Reproducability

Used cheats to teleport into end in creative mode in order to test dragon fight, saw endermen spawning on island. 

Used version 1.20.1-4.1

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19

### Modloader version

Forge

### Logs

https://gist.github.com/BodhiSmith13/cb4819049ad621ab77aa2098dcfab0dc

**Comment by BodhiSmith13** [comment]
"disableDragonAreaSpawns": {
    "desc:": "Disables mob spawning on the Dragon island during the fight: default:true",
    "disableDragonAreaSpawns": true

**Comment by BodhiSmith13** [comment]
Whenever printDragonPhases is set to true, endermen spawn like in Vanilla.

**Comment by BodhiSmith13** [comment]
Whenever I hit the dragon the endermen despawn and then respawn two seconds later

**Comment by someaddons** [comment]
it is because the dragon is no longer considered "in fight" then, it only prevents spawns while at lower than full health
