### ISSUE TITLE
Configuration possibilites?

### ISSUE THREAD

**Issue by Coconmorus** [someaddons/SavageEnderDragon#46]
I know it says that the number of mobs scales with dragon difficulty, would it be possible to be able to adjust attributes such as dragon health, dragon fireball frequency, and amount of mobs spawned, individually of one another?

Another small improvement that could maybe be made is having the spawns not directly in the lightning, I noticed when running this mod, I'd destroy an end crystal, lightning would strike as a phantom spawned above me, and basically one shot the single phantom.

**Comment by someaddons** [comment]
since its all scaling with player count I couldnt add a config to allow setting exact amounts as those wouldnt scale, I can add relative modifiers though, like x2 health

**Comment by someaddons** [comment]
added a bunch in 4.2
