### ISSUE TITLE
[Bug]: 1.20.1 crash mentions dragon fight mixins

### ISSUE THREAD

**Issue by jojofenin99** [someaddons/SavageEnderDragon#47]
### Describe the bug you're experiencing

the game just crashes and mentions dragon fight and it not being able to inject something , btw theres no 1.20.1 option
heres the log: 

### Reproducability

I just started the game i also have the endertrigon mod

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19

### Modloader version

Forge

### Logs

https://gist.github.com/jojofenin99/616771667c5c6d883e09413f7990477e

**Comment by jojofenin99** [comment]
on older version it used to work but now it won't

**Comment by someaddons** [comment]
ye the endertrigon mod seems to have some quite invasive mixins there preventing others from injecting

**Comment by someaddons** [comment]
did add a workaround though
