### ISSUE TITLE
[Bug]: 1.20.1 crash when entities interact with crystals on server

### ISSUE THREAD

**Issue by PhoenixBlue1256** [someaddons/SavageEnderDragon#48]
### Describe the bug you're experiencing

I'm experimenting with the mod on a dedicated server and any entity that interacts with the end crystals causes the game to crash.

I tried multiple different entities including arrows from the base game, void scatter arrows from L_Ender's Cataclysm and throwing a brick which Supplementaries allows you to do which all crashed the game when hitting a crystal, one of the crashes was from the dragons own fireball attacks spreading the effect cloud which promptly crashed the game.

[crash-2024-03-07_20.47.50-server.txt](https://github.com/someaddons/SavageEnderDragon/files/14532369/crash-2024-03-07_20.47.50-server.txt)
[crash-2024-03-07_20.52.08-server.txt](https://github.com/someaddons/SavageEnderDragon/files/14532370/crash-2024-03-07_20.52.08-server.txt)
[crash-2024-03-07_20.56.17-server.txt](https://github.com/someaddons/SavageEnderDragon/files/14532371/crash-2024-03-07_20.56.17-server.txt)
[crash-2024-03-07_21.02.12-server.txt](https://github.com/someaddons/SavageEnderDragon/files/14532372/crash-2024-03-07_21.02.12-server.txt)

### Reproducability

I'm running a dedicated server so that might be part of it. Find and travel through an end portal and after the dragon spawns, shoot or throw any object considered an entity at an end crystal

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19

### Modloader version

Forge

### Logs

https://gist.github.com/PhoenixBlue1256/6056c33e62ff5b6f46b19f0261a9179d

**Comment by Farvox** [comment]
Same
[crash-2024-03-08_16.48.31-server.txt](https://github.com/someaddons/SavageEnderDragon/files/14540189/crash-2024-03-08_16.48.31-server.txt)
