### ISSUE TITLE
[Bug]: server crash:bound must be positive

### ISSUE THREAD

**Issue by badnng** [someaddons/SavageEnderDragon#51]
### Describe the bug you're experiencing

It started the server normally. Someone went to the end and crashed
version:1.20.1-Fabric

### Reproducability

It started the server normally

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19

### Modloader version

Fabric

### Logs

https://gist.github.com/badnng/1c7508b2c2a82158b06ec66717c4e37f

**Comment by someaddons** [comment]
fixed in 4.5, its because the respawn mob list on crystals was empty
