### ISSUE TITLE
[Bug]: Crystals respawn in the incorrect spot when making a new world after fighting the dragon in a different world / Manually placed crystals get saved and respawn

### ISSUE THREAD

**Issue by NolanHewitt** [someaddons/SavageEnderDragon#53]
### Describe the bug you're experiencing

The config saves the crystal location, but when you make a new world these crystal locations won't match up with the new world resulting in crystals either respawning inside the obisidan pillars or in the sky. Making the config read only prevents the file from saving the locations, but then the crystals are still placed in the wrong locations in different worlds if you don't fully restart minecraft before changing worlds. Doing this also makes it so crystals wont respawn at all if you restart minecraft and join the world during the fight before the crystals respawn. Versions before 4.2 had no issues with this. 

The only workaround right now seems to be to manually open the config file and delete the crystal locations and restart minecraft if its already open before making a new world, but this has the issue of you can't have more than one world you're actively playing at a time or the crystal location part of the config will get messed up. I think either the option to disable crystal saving so it functions like 4.1 and before, or having it save crystal locations on a per-world basis instead if possible, could be some solutions.

Also, manually placed crystals get saved to the config and respawn as well which seems...bad. This issue in particular makes me think an option to turn off crystal saving would be the better option.
### Reproducability

Fight the dragon in a world so that the crystal locations get auto saved to the config. Then make a new world and fight the dragon again. Bug occurs

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.20.1

### Modloader version

Fabric

### Logs

https://gist.github.com/NolanHewitt/177e51b6c2f2ae0e8f9ebf81871d42fa

**Comment by someaddons** [comment]
changed it to save per level in 4.6
