### ISSUE TITLE
[Feature request]: Config option to disable fire from lightning strikes

### ISSUE THREAD

**Issue by polykatt** [someaddons/SavageEnderDragon#55]
I think it would be great if there was a way to disable the fire caused by lighting strikes on the ground. There are plenty of mods that add special drops from killing the ender dragon; and of cause if these items drop into the fire they're destroyed. I don't want to completely disable the lighting strikes as it is a good addition, so maybe just the fire if possible.

**Comment by someaddons** [comment]
can't really do that as it would affect any vanilla lightning strike aswell sadly
