### ISSUE TITLE
please provide config option to have endermen agro

### ISSUE THREAD

**Issue by JetpackRescue** [someaddons/SavageEnderDragon#8]
1.16.5
love everything about this mod except it agros endermen on the end island, I want to turn that off because I still want endermen there, but I have other mobs that spawn and the endermen are just annoying when they're all running at you.

a config option to set the amount of endermen that spawn would be nice as well

**Comment by someaddons** [comment]
The dragon spawns aggro endermen attacking the player, you can configure that to be a different entity already. By default normal spawning enderman are disabled for exactly this reason.
